src/Entity/Chef.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ChefRepository")
 */
class Chef
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $Prenom;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }
}

src/Entity/Plat.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PlatRepository")
 */
class Plat
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $Nom;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }
}

src/Entity/Restaurant.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RestaurantRepository")
 */
class Restaurant
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $Chef;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombreEtoile;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getChef(): ?string
    {
        return $this->Chef;
    }

    public function setChef(string $Chef): self
    {
        $this->Chef = $Chef;

        return $this;
    }

    public function getNombreEtoile(): ?int
    {
        return $this->nombreEtoile;
    }

    public function setNombreEtoile(int $nombreEtoile): self
    {
        $this->nombreEtoile = $nombreEtoile;

        return $this;
    }
}

src/Controller/GuideController.php
<?php
namespace App\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

//use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
//extends AbstractController
class GuideController extends AbstractController{
    public function accueil() {
        return $this->render('guide/accueil.html.twig');
    }

    public function menu() {
        return $this->render('guide/menu.html.twig');
    }

    public function restaurants(){
        return $this->render('guide/restaurant.html.twig');
    }

    public function chefs(){
        return $this->render('guide/chef.html.twig');
    }

    public function plats(){
        return $this->render('guide/plat.html.twig');
    }

    public function voirRestaurant($id) {
        $restaurant = $this->getDoctrine()->getRepository(Restaurant::class)->find($id);
        if(!$restaurant)
        throw $this->createNotFoundException('Restaurant[id='.$id.'] inexistante');
        return $this->render('guide/restaurant/voir.html.twig', 
        array('restaurant' => $restaurant));
        }

    /*public function accueil() {
        return new Response("<html><body><h1>Guide Michelin</h1> <p>Trouver un restaurant</p></body></html>");
    }

    public function accueil() {
        return new Response("<html><body><h1>Guide Michelin</h1> <p>Trouver un restaurant</p></body></html>");
    }

    public function accueil() {
        return new Response("<html><body><h1>Guide Michelin</h1> <p>Trouver un restaurant</p></body></html>");
    }*/
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/guide/accueil.html.twig
{% extends "layoutgeneral.html.twig" %}
{% block titre %}
    {{ parent() }} : Accueil
{% endblock %}

{% block contenu %}
    <h3>Bienvenu</h3>
    
    <p><a href="{{ path('guide_menu') }}">Voir le Menu</a></p>
{% endblock %}

templates/guide/menu.html.twig
{% extends "layoutgeneral.html.twig" %}
{% block titre %}
    {{ parent() }} : Menu
{% endblock %}

{% block contenu %}
    <h3>Restaurants</h3>
    
    <p><a href="{{ path('guide_restaurants') }}">Voir les restaurants</a></p>

    <h3>Chefs</h3>
    
    <p><a href="{{ path('guide_chefs') }}">Voir les chefs</a></p>

    <h3>Plats</h3>
    
    <p><a href="{{ path('guide_plats') }}">Voir les plats</a></p>

    <p><a href="{{ path('guide_accueil') }}">Retour à l'accueil</a></p>
{% endblock %}

templates/guide/restaurant.html.twig
{% extends "layoutgeneral.html.twig" %}
{% block titre %}
    {{ parent() }} - ajouter un restaurant
{% endblock %}
{% block contenu %}
    <h3>renseigner les champs ci-dessous</h3>
    
{% endblock %}

templates/guide/restaurant/formulaire.html.twig
{{ form_start(monFormulaire) }}
    {{ form_errors(monFormulaire) }}
    <table>
        <tr>
            <td>{{ form_row(monFormulaire.nom) }}</td>
            <td>{{ form_row(monFormulaire.chef) }}</td>
        </tr><tr>
            <td>{{ form_row(monFormulaire.nombreEtoile) }}</td>
        </tr>
    </table>
{{ form_end(monFormulaire) }}

templates/guide/restaurant/voir.html.twig
{% extends "layoutgeneral.html.twig" %}
{% block titre %}
    {{ parent() }} : Restaurant (id={{ restaurant.id }})
{% endblock %}
{% block contenu %}
<ul>
    <li>Nom {{ restaurant.nom }}</li>
    <li>Chef {{ restaurant.chef }}</li>
    <li>Nombre étoile {{ restaurant.nombre_etoile }}</li>
</ul>
<p><a href="{{ path('restaurant_modifier', { 'id': restaurant.id }) }}">
 modifier le restaurant</a></p>
{% endblock %}

templates/layoutgeneral.html.twig
<!DOCTYPE html>
<html>
    <body>
        <h1>{% block titre %}Guide Michelin
            {% endblock %}
        </h1>
        <div id="contenu" >
            {% block contenu %}
            {% endblock %}
        </div>
        <hr />
        <div id="pied_de_page" >
            <p>&copy; DF.</p>
        </div>
    </body>
</html>